version: "3"
services:
  app:
    container_name: stationSki
    image: medalihz/backend  # Replace with the actual image and tag
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    ports:
      - "8089:8089"  # Map your application's port to the host
    depends_on:
      - mysqldb  # Ensure the MySQL service is started before the application
    volumes:
      - app_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: stationSki
      PROMETHEUS_EXPORTER_ENABLED: "true" # Enable the Prometheus exporter
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  mysqld_exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "root:@tcp(mysqldb:3306)/stationSki"
    ports:
      - "9104:9104"

  angular-app:
    container_name: angular-app
    image: medalihz/frontend  # Replace with your Angular app image
    ports:
      - "4200:4200"  # Map port 4200 from the container to port 4200 on the host

  adminer:
    container_name: adminer
   # image: adminer:latest
    image: adminer:4.6.2
    restart: always
    ports:
      - "8085:8080"

volumes:
    app_data:  # Define the app_data volume
    db:

